name: MindAmp_GUI
channels:
  - conda-forge
dependencies:
  - edflib-python=1.0.6
  - joblib=1.2.0
  - jupyter=1.0.0
  - matplotlib=3.5.2
  - numpy=1.23.1
  - pandas=1.4.3
  - pyqt=5.15.7
  - pyqtgraph=0.12.4
  - python=3.10.5
  - scikit-learn=1.1.3
  - scipy=1.8.1
  - pip=21.3.1
  - mne=1.2.2
  - pyinstaller=5.6.2

  - pip:
    - bleak==0.14.3
    - mlflow==2.0.1
    - pyqt5-sip==12.11.0
    - qasync==0.23.0
    - mlflow==2.0.1
    - mlflow-extend==0.1.6
